name: Sphinx Pages
on:
  push:
    branches:
      - main
      - dev
      - feat/doruk/31 #Temporarily placed to test the documentation on feature branch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy docs to Github Pages
    steps:
      - uses: seanzhengw/sphinx-pages@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          create_readme: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: steps.deployment.outputs.page_url
        uses: actions/deploy-pages@v1
